In [16]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
print(arr2)
arr2.dtype
arr1.sum()

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


np.int64(15)

In [42]:
arr=np.array([[71,69,43,56],[78,62,43,56],[78,67,43,56],[78,67,43,56],[78,67,43,56],[72,67,43,56]])
print(arr)

[[71 69 43 56]
 [78 62 43 56]
 [78 67 43 56]
 [78 67 43 56]
 [78 67 43 56]
 [72 67 43 56]]


In [43]:
#Calculate sum of marks of all students
b=np.sum(arr,axis=1)
print(b)

[239 239 244 244 244 238]


In [45]:
#Calculate average of marks in each subjecct
b=np.mean(arr,axis=0)
print(b)

[75.83333333 66.5        43.         56.        ]


In [50]:
#Calculate max marks in each subject
#axis=0 means column wise
#axis=1 means row wise

b=np.max(arr,axis=0)
print(b)

[78 69 43 56]


In [48]:
#Calculate min marks in each subjecct
b=np.min(arr,axis=0)
print(b)

[71 62 43 56]


In [57]:
#Arithmetic Operations

arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[1. 1. 1. 1.]


In [65]:
#Reshaping a given matrix

arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=arr1.reshape(4,2)
print(arr2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [90]:
#Students Data
arr=np.array([[71,69,43,56],[78,62,43,56],[78,67,43,56],[78,67,43,56],[78,67,43,56],[72,67,43,56]])
print(arr)
print()

#Sum of marks of each students
b=np.sum(arr,axis=1)
print(b)
print()

#Sorted Array
top_students=np.sort(b)
print(top_students)

#Top 3 Students
print("Topper :",top_students[-1:-4:-1])

#Students that failed (marks<50)
labels=np.where(arr<50,"Fail","Pass")
print()
print(labels)

#Students with marks in between 240-245
mar=b[(b>240) & (b<=245)]
print()
print(mar)

[[71 69 43 56]
 [78 62 43 56]
 [78 67 43 56]
 [78 67 43 56]
 [78 67 43 56]
 [72 67 43 56]]

[239 239 244 244 244 238]

[238 239 239 244 244 244]
Topper : [244 244 244]

[['Pass' 'Pass' 'Fail' 'Pass']
 ['Pass' 'Pass' 'Fail' 'Pass']
 ['Pass' 'Pass' 'Fail' 'Pass']
 ['Pass' 'Pass' 'Fail' 'Pass']
 ['Pass' 'Pass' 'Fail' 'Pass']
 ['Pass' 'Pass' 'Fail' 'Pass']]

[244 244 244]


In [81]:
#Reveraing an given array

arr=np.array([1,2,3])
print(arr[::-1])

[3 2 1]


In [106]:
#Product Quaterly sales report where row represent product and column represent sale
product=np.array([[4500,3800,2200,1000],
                  [3500,5800,1200,3000],
                  [2500,1800,5200,4000],
                  [1500,2800,2200,2000]])
print(product)
b=np.sum(product,axis=0)
#Total sale of 2 Product
print(b[1])

#3 Quater Sale Sum of all products
c=np.sum(product,axis=1)
print(c[2])

#Top two performing product
c=np.sort(b)
print(c[-1:-3:-1])

#Product with sale above 13000
row,col=np.where(product>=5000)
print(np.vstack((row,col)))

[[4500 3800 2200 1000]
 [3500 5800 1200 3000]
 [2500 1800 5200 4000]
 [1500 2800 2200 2000]]
14200
13500
[14200 12000]
[[1 2]
 [1 2]]


In [116]:
#Matrix Multiplication
a=np.array([[10,5,-6],
            [7,-4,6],
            [9,9,1]])
b=np.array([5,-8,10])
inv=np.linalg.inv(a)
mul=np.matmul(inv,b)
print(mul)


[-0.25772098  1.38125666 -0.11182109]


In [136]:
#Crammer Rule
a=np.array([[10,5,-6],
            [7,-4,6],
            [9,9,0]])
B=np.array([5,-8,10])
D=np.linalg.det(a)
print("Determinante is: ",D)
A1 = a.copy()
A1[:,0] = B
Dx = np.linalg.det(A1)

A2 = a.copy()
A2[:,1] = B
Dy = np.linalg.det(A2)

A3 = a.copy()
A3[:,2] = B
Dz = np.linalg.det(A3)

x = Dx / D
y = Dy / D
z = Dz / D

print("x =", x)
print("y =", y)
print("z =", z)

Determinante is:  -863.9999999999997
x = -0.25694444444444475
y = 1.3680555555555567
z = -0.12152777777777779


In [138]:
#Crammer Rule for matrices of any order
a=eval(input("Enter the coefficient matrix"))
A=np.array(a)
b=eval(input("Enter the vector matrix"))
B=np.array(b)
D=np.linalg.det(a)
print("Determinante is: ",D)
n=int(input("Enter the no of column of matrix"))
for i in range(n):
    A1=A.copy()
    A1[:,i]=B
    Dx=np.linalg.det(A1)
    print(Dx/D)

Enter the coefficient matrix [(10,5,-6),(7,-4,6),(9,9,0)]
Enter the vector matrix [5,-8,10]


Determinante is:  -863.9999999999997


Enter the no of column of matrix 3


-0.25694444444444475
1.3680555555555567
-0.12152777777777779
